Test unitaire
Qiix/DevOps_Timesheet_2ALINFO4_Devolution pull request #5
Opened 2022-04-06 22:50 UTC by ChaymaJlassi

2022-04-06 22:53 UTC, Qiix commented
ok

2022-04-06 23:00 UTC, Qiix requested changes
remove unnecessary files

2022-04-07 01:13 UTC, YassinMsaad approved these changes

2022-04-07 01:14 UTC, YassinMsaad commented
looks good

2022-04-07 03:09 UTC, closed without merging